---
title: "Fish TP"
author: "Anna Radchenko"
date: "February 16, 2020"
output: html_document
---
```{r}
Cage.Mass <- read.csv("~/Theses Pieces/Tank Pad Pilot Study/Cage Mass.csv")
```

```{r}
mass <- aov(Cage.Mass$Mass ~ Cage.Mass$ï..Tank)
summary(mass)
shapiro.test(residuals(mass))
```

```{r}
mass1 <- aov(Cage.Mass$Mass ~ Cage.Mass$ï..Tank * as.factor(Cage.Mass$Date))
summary(mass1)
```

```{r}
height <- read.csv("~/Theses Pieces/Tank Pad Pilot Study/Tank Height.csv")
```

```{r}
h <- aov(height$Height ~ height$ï..Tank*as.factor(height$Date))
summary(h)

```


```{r}
gill <- read.csv("~/Theses Pieces/Tank Pad Pilot Study/Gill Samples Metrics.csv")
```

```{r}
mass <- aov(gill$Weight ~ gill$Tank*gill$Date)
summary(mass)
```

```{r}
mass1 <- aov(Weight ~ Tank + Cage %in% Tank, data = gill)
summary(mass1)
```

```{r}
length <- aov(Length ~ Tank*Date, data = gill)
summary(length)
TukeyHSD(length)
```

```{r}
length1 <- aov(Length ~ Tank + Cage %in% Tank, data = gill)
summary(length1)
```

```{r}
length2 <- aov(Length ~ Treatment + Tank, data = gill)
summary(length2)
```


```{r}
Chla <- read.csv("~/Theses Pieces/Tank Pad Pilot Study/Post.Chla.csv")
```

```{r}
chl1 <- aov(Chla$Chla ~ as.factor(Chla$Time), subset = Chla$Tank == 'L1')
summary (chl1)
TukeyHSD(chl1)
```

```{r}
chlt <- aov(Chla$Chla ~ as.factor(Chla$Tank), subset = Chla$Time == '0')
summary(chlt)
TukeyHSD(chlt)
```




```{r}
chl2 <- aov(Chla$Chla ~ as.factor(Chla$Time), subset = Chla$Tank == 'L2')
summary (chl2)
TukeyHSD(chl2)
```

```{r}
chl4 <- aov(Chla$Chla ~ as.factor(Chla$Time), subset = Chla$Tank == 'L4')
summary (chl4)
TukeyHSD(chl4)
```


```{r}
chl <- aov(Chla$Chla ~ as.factor(Chla$Tank), subset = Chla$Time == '0')
summary(chl)
TukeyHSD(chl)
```

```{r}
plot(Chla$Chla[Chla$Tank == "L1"] ~ Chla$Time[Chla$Tank =="L1"], type = "o", col ='red', xaxt = "n", yaxt = "n", xlab = "Time Since Ozonation (hours)", ylab = "Chlorophyll a concentration (ug/L)")
lines(Chla$Chla[Chla$Tank =="L2"] ~ Chla$Time[Chla$Tank == "L2"], type = "o", col = "blue")
lines(Chla$Chla[Chla$Tank =="L4"] ~ Chla$Time[Chla$Tank == "L4"], type = "o", col = "green")
axis(1, at = seq(0,72, by =24))
axis(2, at = seq(0,12, by =2))
legend("topright", legend=c("L1", "L2", "L4"), col=c("red", "blue", "green"), lty =1, cex =0.8)


```

```{r}
ann <- read.csv("~/Theses Pieces/Tank Pad Pilot Study/ann.csv")
```


```{r}
boxplot(ann$Nitrate~ann$Time, ylab = 'Nitrate Concentration (ppm)')
```

```{r}
boxplot(ann$Nitrite~ann$Time, ylab = 'Nitrite Concentration (ppm)')
```

```{r}
boxplot(ann$Ammonia~ann$Time, ylab = 'Ammonia Concentration (ppm)')
```

