---
title: "Path Analysis"
author: "Anna Radchenko"
date: "March 1, 2020"
output: html_document
---
```{r}
library(lavaan)
library(semPlot)
library(OpenMx)
library(tidyverse)
library(knitr)
library(kableExtra)
library(GGally)
library (caret)
```


```{r}
gill <- read.csv("~/Theses Pieces/Tank Pad Pilot Study/GillFakeDataSet.csv")
gill$TreatmentF <- factor(gill$Treatment)
gill$TankF <- factor(gill$Tank)
gill$CageF <- factor(gill$Cage)
gill$DateF <- factor(gill$Date)
```




```{r}
plot(Gill.Score ~ TreatmentF, data = gill)
```


```{r}
treatonly <- (lm(Gill.Score ~ as.factor(Treatment), data = gill))
summary(treatonly)
shapiro.test(residuals(treatonly))
```

```{r}
tonly <- aov(Gill.Score ~ as.factor(Treatment), data = gill)
summary(tonly)
TukeyHSD(tonly)
```






```{r}
model1 <- lm(Gill.Score ~ TreatmentF + Condition.Factor + Chla + DO + Max.DO + Salinity + pH + Temp, data = gill)
shapiro.test(residuals(model1))
summary(model1)

```

```{r}
fit <- lm(model1)
ld.vars <- attributes(alias(fit)$Complete)$dimnames[[1]]
ld.vars
```




```{r}
model2 <- lm(Gill.Score ~ Treatment + Temp, data = gill)
summary(model2)
```


```{r}
car::vif(model1)
```

```{r}
gill.na <- na.omit(gill)
gill.na <- data.frame(gill.na)
gill.na$TreatmentF <- gill.na$Treatment
```

```{r}
gill.na[,c(1,
        2,
        "item3",
        "item4")] <-
    lapply(Data[,c("item1",
                   "item2",
                   "item3",
                   "item4")], ordered)
```



```{r}
model <- '

Gill.Score ~ Treatment + Condition.Factor + Max.DO + Chla + pH + Salinity + Height + Temp


'
```





```{r}
fit <- cfa(model, data = gill)
varTable(fit)
summary(fit)
```


```{r}
ch.model <- '

chla ~ treatment + temp + 
```

