---
title: "Linear Model Chlorophyll a analysis"
author: "Anna Radchenko"
date: "March 31, 2020"
output: html_document
---

```{r setup, include=FALSE}
# setup the R enviornment for kniting markdown doc properly
library(knitr)
opts_knit$set(root.dir='../')
```

```{r}
chlwq <- read.csv("./Data/ChlaWQReplicateAcuteData1.csv")
```

```{r}
library(ggplot2)
library(GGally)
library(gridExtra)
library(scatterplot3d)
library(MASS)
library(lubridate)
library(lme4)
library(nlme)
library(vegan)
class(chlwq$Date)
```

```{r}
chlwq$Time <- factor(chlwq$Time, levels = c("Pre", "Post")) #making sure pre always comes before post on figures
chlwq$Chl.a1 <- log(chlwq$Chl.a)
#transforming chlorophyll data since it is not normal
```

```{r}
chlwq$Date <- as.Date(chlwq$Date, "%m.%d.%y")
class(chlwq$Date)
chlwq$Date
#changing class, so that R understands these are dates
```



```{r}
ggpairs(chlwq, columns = c("Treatment", "Chl.a", "Chl.a1", "Temp"), columnLabels =  c("Treatment", "Chl.a", "Chl.a1","Temp"), mapping = aes(color = Tank))
#looking for relationships in the data
```



```{r}
chl <- ggpairs(chlwq, columns = c("Treatment", "Chl.a", "Time", "Tank",  "pH"), columnLabels =  c("Treatment", "Chl.a", "Time", "Tank",  "pH"), mapping = aes(color = Tank))
chl
#looking for relationships in the data
```







```{r}
ggplot(chlwq, aes(Treatment, Chl.a1)) +
  geom_point(aes(col=Date))
  facet_wrap(~Tank)

ggplot(chlwq, aes(Temp, Chl.a1)) +
  geom_point(aes(col=Date)) +
  facet_wrap(~Tank)

ggplot(chlwq, aes(Time, Chl.a1)) +
  geom_point(aes(col=Date)) +
  facet_wrap(~Tank)
```


```{r}
main <- lm(Chl.a1 ~ Treatment + Temp + Time + pH + Salinity + Height + Tank, data = chlwq)
summary(main)
#first model with everything
```

```{r}
main2 <- update(main, . ~ . -Salinity - Height)
summary(main2)
#getting rid of a few variables
```

```{r}
main3 <- update(main2, . ~ . + I(Treatment^2) )
summary(main3)
#recognizing that there might be a quadratic response to the treatment variable
```

```{r}
anova(main, main2)
#comparing models
```

```{r}
anova(main2, main3)
#comparing models
```
```{r}
AIC(main)
AIC(main2)
AIC(main3)
```



```{r}
lin4 <- lmer(Chl.a1 ~ Treatment + Temp + Time + Treatment*Temp +  pH  + (1|Tank)  , data = chlwq)
car::Anova(lin4, type = 3)
#bringing in a linear mixed model that I made in my mixed model rmd to compare to these OLS models
```

```{r}
anova(lin4, main3) #linear model is better than fixed effects
```

```{r}
main4 <- update(main3, .~. + (Treatment^2)*Temp)
summary(main4)
#adding in a temperature interaction effect
```

```{r}
anova(main3, main4)
AIC(main4) #main4 model has a better AIC
```

```{r}
main5 <- update(main4, .~. + Treatment:Tank + Ozone)
summary(main5)
print(main5)
#bringing in an interaction effect between my treatment and each replicate tank
```




```{r}
contrasts(chlwq$Tank) #what this tells me is that intercept is L1 and the coefficient for L2 is the difference from L1 and L4 co from L1
#L1 is the average tank, need to average the replicates across the tanks and fit the model that's where I predict chla for each tank and average them 
```







Also looked at modeling without transformed chlorophyll data and the line fits were worse.


```{r}
par(mfrow = c(2,2))
plot(main4)
```




```{r}
#predict values based on the model and compare them to actual to see how well the model predicts data, compare the two

sim_mod <- lm(Chl.a1 ~ Tank + Treatment + I(Treatment^2) + Temp + 
                  Temp:Treatment + Tank:Treatment +
                  Tank:I(Treatment^2), 
              data = chlwq)
sub_mod <- update(sim_mod, . ~ . - Tank - Tank:Treatment - Tank:I(Treatment^2))
main_mod <- lm(Chl.a1 ~ Treatment + I(Treatment^2), data = chlwq)
summary(sim_mod)
plot(sim_mod)

xrange <- seq(min(chlwq$Treatment), max(chlwq$Treatment), length.out = 100)

tanks <- levels(chlwq$Tank)
plot(Chl.a1 ~ Treatment, data = chlwq, ylim = c(0, 4))
for(i in seq_along(tanks)) {
    lines(xrange, 
          predict(sim_mod, newdata = 
                     data.frame(Tank = tanks[i],
                               Treatment = xrange,
                               Temp = mean(chlwq$Temp))),
          col = i+1)
}
lines(predict(sub_mod, newdata = 
                  data.frame(
                        Treatment = xrange,
                        Temp = mean(chlwq$Temp))),
      lwd = 2)
lines(predict(main_mod, newdata = 
                  data.frame(
                      Treatment = xrange)), col='purple', lwd=4)

avg_pred <- predict(sim_mod, newdata = 
                     data.frame(Tank = rep(tanks, each = 100),
                               Treatment = rep(xrange,
                                               times = 3),
                               Temp = mean(chlwq$Temp)))
avg_pred <- tapply(avg_pred, list(rep(xrange, times = 3)), mean)

lines(xrange, avg_pred, lty = 2, lwd=3)

# obs vs predicted plot

pred <- predict(sim_mod)

plot(chlwq$Chl.a1, pred)
abline(a=0, b=1)

avg_obs <- tapply(chlwq$Chl.a1, list(chlwq$Treatment), mean)
avg_pred <- tapply(pred, list(chlwq$Treatment), mean) 

plot(avg_obs, avg_pred)
abline(a=0, b=1)
```

```{r}
plot(Chl.a1 ~ Treatment, data = chlwq, ylim = c(0, 4), xlab = 'Overall Treatment (%)', ylab = 'log(Chlorophyll Concentration (ug/L))')

    
lines(predict(main_mod, newdata = 
                  data.frame(
                      Treatment = xrange)), col='purple', lwd=4)

avg_pred <- predict(sim_mod, newdata = 
                     data.frame(Tank = rep(tanks, each = 100),
                               Treatment = rep(xrange,
                                               times = 3),
                               Temp = mean(chlwq$Temp)))
avg_pred <- tapply(avg_pred, list(rep(xrange, times = 3)), mean)

lines(xrange, avg_pred, lty = 2, lwd=3)

legend('top', legend=c("Predictor: Treatment", "Full Model"),
       col=c("purple", "black"), lty=1:2, cex=0.8,
       title="Line types", text.font=4, bg='lightblue')


```

```{r}
plot(Chl.a ~ Treatment, data = chlwq, ylim = c(0, 20), xlab = 'Overall Treatment (%)', ylab = 'Chlorophyll Concentration (ug/L)')

    
lines(predict(main_mod, newdata = 
                  data.frame(
                      Treatment = xrange)), col='purple', lwd=4)

avg_pred <- predict(sim_mod, newdata = 
                     data.frame(Tank = rep(tanks, each = 100),
                               Treatment = rep(xrange,
                                               times = 3),
                               Temp = mean(chlwq$Temp)))
avg_pred <- tapply(avg_pred, list(rep(xrange, times = 3)), mean)

lines(xrange, avg_pred, lty = 2, lwd=3)

legend('top', legend=c("Predictor: Treatment", "Full Model"),
       col=c("purple", "black"), lty=1:2, cex=0.8,
       title="Line types", text.font=4, bg='lightblue')
```





```{r}
sim_mod <- lm(Chl.a1 ~ Tank + Treatment + I(Treatment^2) + Temp + 
                  Temp:Treatment + Tank:Treatment +
                  Tank:I(Treatment^2) + Time, 
              data = chlwq)

cc <- sub_mod$coefficients
eqn <- paste("Y =", paste(round(cc[1],2), paste(round(cc[-1],2), names(cc[-1]), sep=" * ", collapse=" + "), sep=" + "), "+ e")
eqn 
#looking at the equation based on the model fit
```

```{r}
Y = 3.16 + -0.06 * 30 + -0.02 * 30 + -0.29 #prediction for post chl.a if temp = 30 and treatment = 30
Y
10^Y 
#having a negative correlation for temperature doesn't makes sense, as a higher temperature should not lower the chlorophyll a concentration left, but increase it
```


```{r}
acf(chlwq$Chl.a) #looking for autocorrelation
#appear to have weak autocorrelation, only a few points outside of the 95% confidence interval
```


```{r}

chladist <- dist(chlwq$Chl.a)
xy_dist <- dist(chlwq$Date)
```


```{r}
max_dist = max(xy_dist) / 2

# plot result
plot(xy_dist, chladist)
abline(lm(chladist ~ xy_dist), lwd=3, col='red')
lines(lowess(xy_dist, chladist), lwd=3, col='pink')
abline(v = max_dist, col='red', lwd=3, lty=2)
```

```{r}
obs_cor = cor(xy_dist, chladist)
obs_cor
```

```{r}
chlamantel = mantel(xy_dist, chladist)
chlamantel
```

```{r}
chl_gls <- gls(Chl.a1 ~ Tank + Treatment + I(Treatment^2) + Temp + 
                  Temp:Treatment + Tank:Treatment +
                  Tank:I(Treatment^2) + Time, 
              data = chlwq)
plot(Variogram (chl_gls))
```

```{r}
chl_exp = update(chl_gls, corr=corExp())
# examine fit of error model to the raw model residuals
# note this function defaults to displaying pearson standardized residuals
# resType='p' or resType='pearson'
plot(Variogram(chl_exp, maxDist = max_dist))
```

```{r}
# that doesn't look so good because clearly the model does not fit the error 
# very well, it appears that there is a nugget (i.e., non-zero y-intercept)
# Let's examine the normalized residuals in which the residuals are 
# devided by the estimate of the variance-covariance matrix. If the model
# fits well these residuals should be normally distributed.
plot(Variogram(chl_exp, resType='normalized', maxDist = max_dist))
```

```{r}
# we see a little bit of a trend in the residuals but not too bad

# let's look at the same model but with a nugget
chl_exp_nug = update(chl_exp, corr=corExp(nugget=T))
plot(Variogram(chl_exp_nug, maxDist = max_dist))
```

```{r}
plot(Variogram(chl_exp_nug, resType='n', maxDist = max_dist))
```

```{r}
# those look like they provide a better fit to the data

# let's examine the rational quadratic error model
chl_rat_nug = update(chl_gls, corr=corRatio(nugget=T))
# examine fit of error model to model residuals
plot(Variogram(chl_rat_nug, maxDist = max_dist))
```

```{r}
plot(Variogram(chl_rat_nug, resType='n', maxDist = max_dist))
```

```{r}
# this model seems to fit about as a good as the exponential with the nugget

# let's compare the models
anova(chl_gls, chl_exp, chl_exp_nug, chl_rat_nug, test=F)
```

```{r}
#it appears that hte exponential model is the best followed closely by the exponential and rational models with nuggests
summary(chl_exp)
```

```{r}
anova(main5, chl_exp)
```




```{r}
main6 <- update(main5,  .~. - pH - Time - Tank - Tank:Treatment)
summary(main6)
cc <- main6$coefficients
eqn <- paste("Y =", paste(round(cc[1],2), paste(round(cc[-1],2), names(cc[-1]), sep=" * ", collapse=" + "), sep=" + "), "+ e")
eqn 
#looking at the equation based on the model fit
```

```{r}
Y = 0.47 + (-0.16 * 20) + (0.31 * 30) + (-0.01 * 20^2) + -2.45  + (-0.01)
#treatment = 20, temp = 30
Y
10^Y

```

```{r}

```

